name = "GradDescent"
uuid = "76767984-a792-11e8-2bb2-77d388f79a09"
authors = ["Theo Galy-Fajou <theo.galyfajou@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
